//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ConcertFinderModel", "FK_EVENT_LOCATION", "T_Location", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConcertFinderMVC.DataAccess.T_Location), "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Event))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "FK_EVENT_USER", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConcertFinderMVC.DataAccess.T_User), "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Event))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_HasNotification", "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Event), "T_Notification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Notification))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_HasTags", "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Event), "T_Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Tag))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_Notified", "T_Notification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Notification), "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_User))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_Prefer", "T_Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_Tag), "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConcertFinderMVC.DataAccess.T_User))]

#endregion

namespace ConcertFinderMVC.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConcertFinderEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConcertFinderEntities object using the connection string found in the 'ConcertFinderEntities' section of the application configuration file.
        /// </summary>
        public ConcertFinderEntities() : base("name=ConcertFinderEntities", "ConcertFinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConcertFinderEntities object.
        /// </summary>
        public ConcertFinderEntities(string connectionString) : base(connectionString, "ConcertFinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConcertFinderEntities object.
        /// </summary>
        public ConcertFinderEntities(EntityConnection connection) : base(connection, "ConcertFinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Event> T_Event
        {
            get
            {
                if ((_T_Event == null))
                {
                    _T_Event = base.CreateObjectSet<T_Event>("T_Event");
                }
                return _T_Event;
            }
        }
        private ObjectSet<T_Event> _T_Event;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Location> T_Location
        {
            get
            {
                if ((_T_Location == null))
                {
                    _T_Location = base.CreateObjectSet<T_Location>("T_Location");
                }
                return _T_Location;
            }
        }
        private ObjectSet<T_Location> _T_Location;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Notification> T_Notification
        {
            get
            {
                if ((_T_Notification == null))
                {
                    _T_Notification = base.CreateObjectSet<T_Notification>("T_Notification");
                }
                return _T_Notification;
            }
        }
        private ObjectSet<T_Notification> _T_Notification;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Tag> T_Tag
        {
            get
            {
                if ((_T_Tag == null))
                {
                    _T_Tag = base.CreateObjectSet<T_Tag>("T_Tag");
                }
                return _T_Tag;
            }
        }
        private ObjectSet<T_Tag> _T_Tag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_User> T_User
        {
            get
            {
                if ((_T_User == null))
                {
                    _T_User = base.CreateObjectSet<T_User>("T_User");
                }
                return _T_User;
            }
        }
        private ObjectSet<T_User> _T_User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Event EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Event(T_Event t_Event)
        {
            base.AddObject("T_Event", t_Event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Location EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Location(T_Location t_Location)
        {
            base.AddObject("T_Location", t_Location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Notification EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Notification(T_Notification t_Notification)
        {
            base.AddObject("T_Notification", t_Notification);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Tag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Tag(T_Tag t_Tag)
        {
            base.AddObject("T_Tag", t_Tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_User(T_User t_User)
        {
            base.AddObject("T_User", t_User);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Event object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateDebut">Initial value of the DateDebut property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="titre">Initial value of the Titre property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static T_Event CreateT_Event(global::System.Int64 id, global::System.DateTime dateDebut, global::System.String description, global::System.String titre, global::System.String type)
        {
            T_Event t_Event = new T_Event();
            t_Event.Id = id;
            t_Event.DateDebut = dateDebut;
            t_Event.Description = description;
            t_Event.Titre = titre;
            t_Event.Type = type;
            return t_Event;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateDebut
        {
            get
            {
                return _DateDebut;
            }
            set
            {
                OnDateDebutChanging(value);
                ReportPropertyChanging("DateDebut");
                _DateDebut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDebut");
                OnDateDebutChanged();
            }
        }
        private global::System.DateTime _DateDebut;
        partial void OnDateDebutChanging(global::System.DateTime value);
        partial void OnDateDebutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateFin
        {
            get
            {
                return _DateFin;
            }
            set
            {
                OnDateFinChanging(value);
                ReportPropertyChanging("DateFin");
                _DateFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateFin");
                OnDateFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateFin;
        partial void OnDateFinChanging(Nullable<global::System.DateTime> value);
        partial void OnDateFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titre
        {
            get
            {
                return _Titre;
            }
            set
            {
                OnTitreChanging(value);
                ReportPropertyChanging("Titre");
                _Titre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titre");
                OnTitreChanged();
            }
        }
        private global::System.String _Titre;
        partial void OnTitreChanging(global::System.String value);
        partial void OnTitreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Valide
        {
            get
            {
                return _Valide;
            }
            set
            {
                OnValideChanging(value);
                ReportPropertyChanging("Valide");
                _Valide = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valide");
                OnValideChanged();
            }
        }
        private Nullable<global::System.Boolean> _Valide;
        partial void OnValideChanging(Nullable<global::System.Boolean> value);
        partial void OnValideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebSite
        {
            get
            {
                return _WebSite;
            }
            set
            {
                OnWebSiteChanging(value);
                ReportPropertyChanging("WebSite");
                _WebSite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebSite");
                OnWebSiteChanged();
            }
        }
        private global::System.String _WebSite;
        partial void OnWebSiteChanging(global::System.String value);
        partial void OnWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreation;
        partial void OnDateCreationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_LOCATION", "T_Location")]
        public T_Location T_Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION", "T_Location").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION", "T_Location").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Location> T_LocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION", "T_Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION", "T_Location", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_USER", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER", "T_User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasNotification", "T_Notification")]
        public EntityCollection<T_Notification> T_Notification
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Notification>("ConcertFinderModel.T_HasNotification", "T_Notification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Notification>("ConcertFinderModel.T_HasNotification", "T_Notification", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasTags", "T_Tag")]
        public EntityCollection<T_Tag> T_Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Tag>("ConcertFinderModel.T_HasTags", "T_Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Tag>("ConcertFinderModel.T_HasTags", "T_Tag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Location object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="ville">Initial value of the Ville property.</param>
        /// <param name="pays">Initial value of the Pays property.</param>
        /// <param name="rue">Initial value of the Rue property.</param>
        /// <param name="cP">Initial value of the CP property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        public static T_Location CreateT_Location(global::System.Int64 id, global::System.String name, global::System.String ville, global::System.String pays, global::System.String rue, global::System.String cP, global::System.Double latitude, global::System.Double longitude)
        {
            T_Location t_Location = new T_Location();
            t_Location.Id = id;
            t_Location.Name = name;
            t_Location.Ville = ville;
            t_Location.Pays = pays;
            t_Location.Rue = rue;
            t_Location.CP = cP;
            t_Location.Latitude = latitude;
            t_Location.Longitude = longitude;
            return t_Location;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ville
        {
            get
            {
                return _Ville;
            }
            set
            {
                OnVilleChanging(value);
                ReportPropertyChanging("Ville");
                _Ville = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ville");
                OnVilleChanged();
            }
        }
        private global::System.String _Ville;
        partial void OnVilleChanging(global::System.String value);
        partial void OnVilleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pays
        {
            get
            {
                return _Pays;
            }
            set
            {
                OnPaysChanging(value);
                ReportPropertyChanging("Pays");
                _Pays = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pays");
                OnPaysChanged();
            }
        }
        private global::System.String _Pays;
        partial void OnPaysChanging(global::System.String value);
        partial void OnPaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rue
        {
            get
            {
                return _Rue;
            }
            set
            {
                OnRueChanging(value);
                ReportPropertyChanging("Rue");
                _Rue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rue");
                OnRueChanged();
            }
        }
        private global::System.String _Rue;
        partial void OnRueChanging(global::System.String value);
        partial void OnRueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CP
        {
            get
            {
                return _CP;
            }
            set
            {
                OnCPChanging(value);
                ReportPropertyChanging("CP");
                _CP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CP");
                OnCPChanged();
            }
        }
        private global::System.String _CP;
        partial void OnCPChanging(global::System.String value);
        partial void OnCPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Double _Latitude;
        partial void OnLatitudeChanging(global::System.Double value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Double _Longitude;
        partial void OnLongitudeChanging(global::System.Double value);
        partial void OnLongitudeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_LOCATION", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_LOCATION", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_LOCATION", "T_Event", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Notification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Notification : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Notification object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="titre">Initial value of the Titre property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        public static T_Notification CreateT_Notification(global::System.Int64 id, global::System.String titre, global::System.DateTime date, global::System.String message)
        {
            T_Notification t_Notification = new T_Notification();
            t_Notification.Id = id;
            t_Notification.Titre = titre;
            t_Notification.Date = date;
            t_Notification.Message = message;
            return t_Notification;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titre
        {
            get
            {
                return _Titre;
            }
            set
            {
                OnTitreChanging(value);
                ReportPropertyChanging("Titre");
                _Titre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titre");
                OnTitreChanged();
            }
        }
        private global::System.String _Titre;
        partial void OnTitreChanging(global::System.String value);
        partial void OnTitreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasNotification", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.T_HasNotification", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.T_HasNotification", "T_Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Notified", "T_User")]
        public EntityCollection<T_User> T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_User>("ConcertFinderModel.T_Notified", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_User>("ConcertFinderModel.T_Notified", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Tag object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static T_Tag CreateT_Tag(global::System.Int64 id, global::System.String name)
        {
            T_Tag t_Tag = new T_Tag();
            t_Tag.Id = id;
            t_Tag.Name = name;
            return t_Tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasTags", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.T_HasTags", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.T_HasTags", "T_Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Prefer", "T_User")]
        public EntityCollection<T_User> T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_User>("ConcertFinderModel.T_Prefer", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_User>("ConcertFinderModel.T_Prefer", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="firstname">Initial value of the Firstname property.</param>
        /// <param name="mail">Initial value of the Mail property.</param>
        /// <param name="pseudo">Initial value of the Pseudo property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        public static T_User CreateT_User(global::System.Int64 id, global::System.String name, global::System.String firstname, global::System.String mail, global::System.String pseudo, global::System.String password, global::System.String role, global::System.Byte[] deleted)
        {
            T_User t_User = new T_User();
            t_User.Id = id;
            t_User.Name = name;
            t_User.Firstname = firstname;
            t_User.Mail = mail;
            t_User.Pseudo = pseudo;
            t_User.Password = password;
            t_User.Role = role;
            t_User.Deleted = deleted;
            return t_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pseudo
        {
            get
            {
                return _Pseudo;
            }
            set
            {
                OnPseudoChanging(value);
                ReportPropertyChanging("Pseudo");
                _Pseudo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pseudo");
                OnPseudoChanged();
            }
        }
        private global::System.String _Pseudo;
        partial void OnPseudoChanging(global::System.String value);
        partial void OnPseudoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ville
        {
            get
            {
                return _Ville;
            }
            set
            {
                OnVilleChanging(value);
                ReportPropertyChanging("Ville");
                _Ville = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ville");
                OnVilleChanged();
            }
        }
        private global::System.String _Ville;
        partial void OnVilleChanging(global::System.String value);
        partial void OnVilleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Deleted
        {
            get
            {
                return StructuralObject.GetValidValue(_Deleted);
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Byte[] _Deleted;
        partial void OnDeletedChanging(global::System.Byte[] value);
        partial void OnDeletedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_USER", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_USER", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_USER", "T_Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Notified", "T_Notification")]
        public EntityCollection<T_Notification> T_Notification
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Notification>("ConcertFinderModel.T_Notified", "T_Notification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Notification>("ConcertFinderModel.T_Notified", "T_Notification", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Prefer", "T_Tag")]
        public EntityCollection<T_Tag> T_Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Tag>("ConcertFinderModel.T_Prefer", "T_Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Tag>("ConcertFinderModel.T_Prefer", "T_Tag", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
