//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ConcertFinderModel", "FK_EVENT_LOCATION1", "T_Location", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BackEndAdmin.T_Location), "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Event))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "FK_EVENT_USER1", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BackEndAdmin.T_User), "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Event))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_HasNotification", "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Event), "T_Notification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Notification))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_HasTags", "T_Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Event), "T_Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Tag))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_Notified", "T_Notification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Notification), "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_User))]
[assembly: EdmRelationshipAttribute("ConcertFinderModel", "T_Prefer", "T_Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_Tag), "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BackEndAdmin.T_User))]

#endregion

namespace BackEndAdmin
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConcertFinderEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConcertFinderEntities object using the connection string found in the 'ConcertFinderEntities' section of the application configuration file.
        /// </summary>
        public ConcertFinderEntities() : base("name=ConcertFinderEntities", "ConcertFinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConcertFinderEntities object.
        /// </summary>
        public ConcertFinderEntities(string connectionString) : base(connectionString, "ConcertFinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConcertFinderEntities object.
        /// </summary>
        public ConcertFinderEntities(EntityConnection connection) : base(connection, "ConcertFinderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Event> T_Event
        {
            get
            {
                if ((_T_Event == null))
                {
                    _T_Event = base.CreateObjectSet<T_Event>("T_Event");
                }
                return _T_Event;
            }
        }
        private ObjectSet<T_Event> _T_Event;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Location> T_Location
        {
            get
            {
                if ((_T_Location == null))
                {
                    _T_Location = base.CreateObjectSet<T_Location>("T_Location");
                }
                return _T_Location;
            }
        }
        private ObjectSet<T_Location> _T_Location;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Notification> T_Notification
        {
            get
            {
                if ((_T_Notification == null))
                {
                    _T_Notification = base.CreateObjectSet<T_Notification>("T_Notification");
                }
                return _T_Notification;
            }
        }
        private ObjectSet<T_Notification> _T_Notification;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Tag> T_Tag
        {
            get
            {
                if ((_T_Tag == null))
                {
                    _T_Tag = base.CreateObjectSet<T_Tag>("T_Tag");
                }
                return _T_Tag;
            }
        }
        private ObjectSet<T_Tag> _T_Tag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_User> T_User
        {
            get
            {
                if ((_T_User == null))
                {
                    _T_User = base.CreateObjectSet<T_User>("T_User");
                }
                return _T_User;
            }
        }
        private ObjectSet<T_User> _T_User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Event EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Event(T_Event t_Event)
        {
            base.AddObject("T_Event", t_Event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Location EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Location(T_Location t_Location)
        {
            base.AddObject("T_Location", t_Location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Notification EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Notification(T_Notification t_Notification)
        {
            base.AddObject("T_Notification", t_Notification);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Tag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Tag(T_Tag t_Tag)
        {
            base.AddObject("T_Tag", t_Tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_User(T_User t_User)
        {
            base.AddObject("T_User", t_User);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Event object.
        /// </summary>
        /// <param name="eVENT_ID">Initial value of the EVENT_ID property.</param>
        /// <param name="eVENT_DATEDEBUT">Initial value of the EVENT_DATEDEBUT property.</param>
        /// <param name="eVENT_DESCRIPTION">Initial value of the EVENT_DESCRIPTION property.</param>
        /// <param name="eVENT_TITRE">Initial value of the EVENT_TITRE property.</param>
        /// <param name="eVENT_TYPE">Initial value of the EVENT_TYPE property.</param>
        public static T_Event CreateT_Event(global::System.Int64 eVENT_ID, global::System.DateTime eVENT_DATEDEBUT, global::System.String eVENT_DESCRIPTION, global::System.String eVENT_TITRE, global::System.String eVENT_TYPE)
        {
            T_Event t_Event = new T_Event();
            t_Event.EVENT_ID = eVENT_ID;
            t_Event.EVENT_DATEDEBUT = eVENT_DATEDEBUT;
            t_Event.EVENT_DESCRIPTION = eVENT_DESCRIPTION;
            t_Event.EVENT_TITRE = eVENT_TITRE;
            t_Event.EVENT_TYPE = eVENT_TYPE;
            return t_Event;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EVENT_ID
        {
            get
            {
                return _EVENT_ID;
            }
            set
            {
                if (_EVENT_ID != value)
                {
                    OnEVENT_IDChanging(value);
                    ReportPropertyChanging("EVENT_ID");
                    _EVENT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EVENT_ID");
                    OnEVENT_IDChanged();
                }
            }
        }
        private global::System.Int64 _EVENT_ID;
        partial void OnEVENT_IDChanging(global::System.Int64 value);
        partial void OnEVENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EVENT_DATEDEBUT
        {
            get
            {
                return _EVENT_DATEDEBUT;
            }
            set
            {
                OnEVENT_DATEDEBUTChanging(value);
                ReportPropertyChanging("EVENT_DATEDEBUT");
                _EVENT_DATEDEBUT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EVENT_DATEDEBUT");
                OnEVENT_DATEDEBUTChanged();
            }
        }
        private global::System.DateTime _EVENT_DATEDEBUT;
        partial void OnEVENT_DATEDEBUTChanging(global::System.DateTime value);
        partial void OnEVENT_DATEDEBUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EVENT_DATEFIN
        {
            get
            {
                return _EVENT_DATEFIN;
            }
            set
            {
                OnEVENT_DATEFINChanging(value);
                ReportPropertyChanging("EVENT_DATEFIN");
                _EVENT_DATEFIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EVENT_DATEFIN");
                OnEVENT_DATEFINChanged();
            }
        }
        private Nullable<global::System.DateTime> _EVENT_DATEFIN;
        partial void OnEVENT_DATEFINChanging(Nullable<global::System.DateTime> value);
        partial void OnEVENT_DATEFINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EVENT_DESCRIPTION
        {
            get
            {
                return _EVENT_DESCRIPTION;
            }
            set
            {
                OnEVENT_DESCRIPTIONChanging(value);
                ReportPropertyChanging("EVENT_DESCRIPTION");
                _EVENT_DESCRIPTION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EVENT_DESCRIPTION");
                OnEVENT_DESCRIPTIONChanged();
            }
        }
        private global::System.String _EVENT_DESCRIPTION;
        partial void OnEVENT_DESCRIPTIONChanging(global::System.String value);
        partial void OnEVENT_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EVENT_TITRE
        {
            get
            {
                return _EVENT_TITRE;
            }
            set
            {
                OnEVENT_TITREChanging(value);
                ReportPropertyChanging("EVENT_TITRE");
                _EVENT_TITRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EVENT_TITRE");
                OnEVENT_TITREChanged();
            }
        }
        private global::System.String _EVENT_TITRE;
        partial void OnEVENT_TITREChanging(global::System.String value);
        partial void OnEVENT_TITREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EVENT_TYPE
        {
            get
            {
                return _EVENT_TYPE;
            }
            set
            {
                OnEVENT_TYPEChanging(value);
                ReportPropertyChanging("EVENT_TYPE");
                _EVENT_TYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EVENT_TYPE");
                OnEVENT_TYPEChanged();
            }
        }
        private global::System.String _EVENT_TYPE;
        partial void OnEVENT_TYPEChanging(global::System.String value);
        partial void OnEVENT_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENT_IMG_PATH
        {
            get
            {
                return _EVENT_IMG_PATH;
            }
            set
            {
                OnEVENT_IMG_PATHChanging(value);
                ReportPropertyChanging("EVENT_IMG_PATH");
                _EVENT_IMG_PATH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENT_IMG_PATH");
                OnEVENT_IMG_PATHChanged();
            }
        }
        private global::System.String _EVENT_IMG_PATH;
        partial void OnEVENT_IMG_PATHChanging(global::System.String value);
        partial void OnEVENT_IMG_PATHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EVENT_VALIDE
        {
            get
            {
                return _EVENT_VALIDE;
            }
            set
            {
                OnEVENT_VALIDEChanging(value);
                ReportPropertyChanging("EVENT_VALIDE");
                _EVENT_VALIDE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EVENT_VALIDE");
                OnEVENT_VALIDEChanged();
            }
        }
        private Nullable<global::System.Boolean> _EVENT_VALIDE;
        partial void OnEVENT_VALIDEChanging(Nullable<global::System.Boolean> value);
        partial void OnEVENT_VALIDEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENT_EMAIL
        {
            get
            {
                return _EVENT_EMAIL;
            }
            set
            {
                OnEVENT_EMAILChanging(value);
                ReportPropertyChanging("EVENT_EMAIL");
                _EVENT_EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENT_EMAIL");
                OnEVENT_EMAILChanged();
            }
        }
        private global::System.String _EVENT_EMAIL;
        partial void OnEVENT_EMAILChanging(global::System.String value);
        partial void OnEVENT_EMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENT_TEL
        {
            get
            {
                return _EVENT_TEL;
            }
            set
            {
                OnEVENT_TELChanging(value);
                ReportPropertyChanging("EVENT_TEL");
                _EVENT_TEL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENT_TEL");
                OnEVENT_TELChanged();
            }
        }
        private global::System.String _EVENT_TEL;
        partial void OnEVENT_TELChanging(global::System.String value);
        partial void OnEVENT_TELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENT_SITE
        {
            get
            {
                return _EVENT_SITE;
            }
            set
            {
                OnEVENT_SITEChanging(value);
                ReportPropertyChanging("EVENT_SITE");
                _EVENT_SITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENT_SITE");
                OnEVENT_SITEChanged();
            }
        }
        private global::System.String _EVENT_SITE;
        partial void OnEVENT_SITEChanging(global::System.String value);
        partial void OnEVENT_SITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Event_DateCreation
        {
            get
            {
                return _Event_DateCreation;
            }
            set
            {
                OnEvent_DateCreationChanging(value);
                ReportPropertyChanging("Event_DateCreation");
                _Event_DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Event_DateCreation");
                OnEvent_DateCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _Event_DateCreation;
        partial void OnEvent_DateCreationChanging(Nullable<global::System.DateTime> value);
        partial void OnEvent_DateCreationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_LOCATION1", "T_Location")]
        public T_Location T_Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION1", "T_Location").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION1", "T_Location").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Location> T_LocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION1", "T_Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Location>("ConcertFinderModel.FK_EVENT_LOCATION1", "T_Location", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_USER1", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER1", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER1", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER1", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("ConcertFinderModel.FK_EVENT_USER1", "T_User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasNotification", "T_Notification")]
        public EntityCollection<T_Notification> T_Notification
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Notification>("ConcertFinderModel.T_HasNotification", "T_Notification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Notification>("ConcertFinderModel.T_HasNotification", "T_Notification", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasTags", "T_Tag")]
        public EntityCollection<T_Tag> T_Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Tag>("ConcertFinderModel.T_HasTags", "T_Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Tag>("ConcertFinderModel.T_HasTags", "T_Tag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Location object.
        /// </summary>
        /// <param name="lOCATION_ID">Initial value of the LOCATION_ID property.</param>
        /// <param name="lOCATION_NAME">Initial value of the LOCATION_NAME property.</param>
        /// <param name="lOCATION_VILLE">Initial value of the LOCATION_VILLE property.</param>
        /// <param name="lOCATION_PAYS">Initial value of the LOCATION_PAYS property.</param>
        /// <param name="lOCATION_RUE">Initial value of the LOCATION_RUE property.</param>
        /// <param name="lOCATION_CP">Initial value of the LOCATION_CP property.</param>
        public static T_Location CreateT_Location(global::System.Int64 lOCATION_ID, global::System.String lOCATION_NAME, global::System.String lOCATION_VILLE, global::System.String lOCATION_PAYS, global::System.String lOCATION_RUE, global::System.String lOCATION_CP)
        {
            T_Location t_Location = new T_Location();
            t_Location.LOCATION_ID = lOCATION_ID;
            t_Location.LOCATION_NAME = lOCATION_NAME;
            t_Location.LOCATION_VILLE = lOCATION_VILLE;
            t_Location.LOCATION_PAYS = lOCATION_PAYS;
            t_Location.LOCATION_RUE = lOCATION_RUE;
            t_Location.LOCATION_CP = lOCATION_CP;
            return t_Location;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 LOCATION_ID
        {
            get
            {
                return _LOCATION_ID;
            }
            set
            {
                if (_LOCATION_ID != value)
                {
                    OnLOCATION_IDChanging(value);
                    ReportPropertyChanging("LOCATION_ID");
                    _LOCATION_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LOCATION_ID");
                    OnLOCATION_IDChanged();
                }
            }
        }
        private global::System.Int64 _LOCATION_ID;
        partial void OnLOCATION_IDChanging(global::System.Int64 value);
        partial void OnLOCATION_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOCATION_NAME
        {
            get
            {
                return _LOCATION_NAME;
            }
            set
            {
                OnLOCATION_NAMEChanging(value);
                ReportPropertyChanging("LOCATION_NAME");
                _LOCATION_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOCATION_NAME");
                OnLOCATION_NAMEChanged();
            }
        }
        private global::System.String _LOCATION_NAME;
        partial void OnLOCATION_NAMEChanging(global::System.String value);
        partial void OnLOCATION_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOCATION_VILLE
        {
            get
            {
                return _LOCATION_VILLE;
            }
            set
            {
                OnLOCATION_VILLEChanging(value);
                ReportPropertyChanging("LOCATION_VILLE");
                _LOCATION_VILLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOCATION_VILLE");
                OnLOCATION_VILLEChanged();
            }
        }
        private global::System.String _LOCATION_VILLE;
        partial void OnLOCATION_VILLEChanging(global::System.String value);
        partial void OnLOCATION_VILLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOCATION_PAYS
        {
            get
            {
                return _LOCATION_PAYS;
            }
            set
            {
                OnLOCATION_PAYSChanging(value);
                ReportPropertyChanging("LOCATION_PAYS");
                _LOCATION_PAYS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOCATION_PAYS");
                OnLOCATION_PAYSChanged();
            }
        }
        private global::System.String _LOCATION_PAYS;
        partial void OnLOCATION_PAYSChanging(global::System.String value);
        partial void OnLOCATION_PAYSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOCATION_RUE
        {
            get
            {
                return _LOCATION_RUE;
            }
            set
            {
                OnLOCATION_RUEChanging(value);
                ReportPropertyChanging("LOCATION_RUE");
                _LOCATION_RUE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOCATION_RUE");
                OnLOCATION_RUEChanged();
            }
        }
        private global::System.String _LOCATION_RUE;
        partial void OnLOCATION_RUEChanging(global::System.String value);
        partial void OnLOCATION_RUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOCATION_CP
        {
            get
            {
                return _LOCATION_CP;
            }
            set
            {
                OnLOCATION_CPChanging(value);
                ReportPropertyChanging("LOCATION_CP");
                _LOCATION_CP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOCATION_CP");
                OnLOCATION_CPChanged();
            }
        }
        private global::System.String _LOCATION_CP;
        partial void OnLOCATION_CPChanging(global::System.String value);
        partial void OnLOCATION_CPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LOCATION_LATTITUDE
        {
            get
            {
                return _LOCATION_LATTITUDE;
            }
            set
            {
                OnLOCATION_LATTITUDEChanging(value);
                ReportPropertyChanging("LOCATION_LATTITUDE");
                _LOCATION_LATTITUDE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOCATION_LATTITUDE");
                OnLOCATION_LATTITUDEChanged();
            }
        }
        private Nullable<global::System.Double> _LOCATION_LATTITUDE;
        partial void OnLOCATION_LATTITUDEChanging(Nullable<global::System.Double> value);
        partial void OnLOCATION_LATTITUDEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LOCATION_LONGITUDE
        {
            get
            {
                return _LOCATION_LONGITUDE;
            }
            set
            {
                OnLOCATION_LONGITUDEChanging(value);
                ReportPropertyChanging("LOCATION_LONGITUDE");
                _LOCATION_LONGITUDE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOCATION_LONGITUDE");
                OnLOCATION_LONGITUDEChanged();
            }
        }
        private Nullable<global::System.Double> _LOCATION_LONGITUDE;
        partial void OnLOCATION_LONGITUDEChanging(Nullable<global::System.Double> value);
        partial void OnLOCATION_LONGITUDEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_LOCATION1", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_LOCATION1", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_LOCATION1", "T_Event", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Notification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Notification : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Notification object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="titre">Initial value of the Titre property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        public static T_Notification CreateT_Notification(global::System.Int64 id, global::System.String titre, global::System.DateTime date, global::System.String message)
        {
            T_Notification t_Notification = new T_Notification();
            t_Notification.Id = id;
            t_Notification.Titre = titre;
            t_Notification.Date = date;
            t_Notification.Message = message;
            return t_Notification;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titre
        {
            get
            {
                return _Titre;
            }
            set
            {
                OnTitreChanging(value);
                ReportPropertyChanging("Titre");
                _Titre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titre");
                OnTitreChanged();
            }
        }
        private global::System.String _Titre;
        partial void OnTitreChanging(global::System.String value);
        partial void OnTitreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasNotification", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.T_HasNotification", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.T_HasNotification", "T_Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Notified", "T_User")]
        public EntityCollection<T_User> T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_User>("ConcertFinderModel.T_Notified", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_User>("ConcertFinderModel.T_Notified", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Tag object.
        /// </summary>
        /// <param name="tAG_ID">Initial value of the TAG_ID property.</param>
        /// <param name="tAG_CONTENT">Initial value of the TAG_CONTENT property.</param>
        public static T_Tag CreateT_Tag(global::System.Int64 tAG_ID, global::System.String tAG_CONTENT)
        {
            T_Tag t_Tag = new T_Tag();
            t_Tag.TAG_ID = tAG_ID;
            t_Tag.TAG_CONTENT = tAG_CONTENT;
            return t_Tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TAG_ID
        {
            get
            {
                return _TAG_ID;
            }
            set
            {
                if (_TAG_ID != value)
                {
                    OnTAG_IDChanging(value);
                    ReportPropertyChanging("TAG_ID");
                    _TAG_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TAG_ID");
                    OnTAG_IDChanged();
                }
            }
        }
        private global::System.Int64 _TAG_ID;
        partial void OnTAG_IDChanging(global::System.Int64 value);
        partial void OnTAG_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TAG_CONTENT
        {
            get
            {
                return _TAG_CONTENT;
            }
            set
            {
                OnTAG_CONTENTChanging(value);
                ReportPropertyChanging("TAG_CONTENT");
                _TAG_CONTENT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TAG_CONTENT");
                OnTAG_CONTENTChanged();
            }
        }
        private global::System.String _TAG_CONTENT;
        partial void OnTAG_CONTENTChanging(global::System.String value);
        partial void OnTAG_CONTENTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_HasTags", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.T_HasTags", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.T_HasTags", "T_Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Prefer", "T_User")]
        public EntityCollection<T_User> T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_User>("ConcertFinderModel.T_Prefer", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_User>("ConcertFinderModel.T_Prefer", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConcertFinderModel", Name="T_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="firstname">Initial value of the Firstname property.</param>
        /// <param name="mail">Initial value of the Mail property.</param>
        /// <param name="pseudo">Initial value of the Pseudo property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        public static T_User CreateT_User(global::System.Int64 id, global::System.String name, global::System.String firstname, global::System.String mail, global::System.String pseudo, global::System.String password, global::System.String role)
        {
            T_User t_User = new T_User();
            t_User.Id = id;
            t_User.Name = name;
            t_User.Firstname = firstname;
            t_User.Mail = mail;
            t_User.Pseudo = pseudo;
            t_User.Password = password;
            t_User.Role = role;
            return t_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pseudo
        {
            get
            {
                return _Pseudo;
            }
            set
            {
                OnPseudoChanging(value);
                ReportPropertyChanging("Pseudo");
                _Pseudo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pseudo");
                OnPseudoChanged();
            }
        }
        private global::System.String _Pseudo;
        partial void OnPseudoChanging(global::System.String value);
        partial void OnPseudoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ville
        {
            get
            {
                return _Ville;
            }
            set
            {
                OnVilleChanging(value);
                ReportPropertyChanging("Ville");
                _Ville = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ville");
                OnVilleChanged();
            }
        }
        private global::System.String _Ville;
        partial void OnVilleChanging(global::System.String value);
        partial void OnVilleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Deleted
        {
            get
            {
                return StructuralObject.GetValidValue(_Deleted);
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Byte[] _Deleted;
        partial void OnDeletedChanging(global::System.Byte[] value);
        partial void OnDeletedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "FK_EVENT_USER1", "T_Event")]
        public EntityCollection<T_Event> T_Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_USER1", "T_Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Event>("ConcertFinderModel.FK_EVENT_USER1", "T_Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Notified", "T_Notification")]
        public EntityCollection<T_Notification> T_Notification
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Notification>("ConcertFinderModel.T_Notified", "T_Notification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Notification>("ConcertFinderModel.T_Notified", "T_Notification", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConcertFinderModel", "T_Prefer", "T_Tag")]
        public EntityCollection<T_Tag> T_Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Tag>("ConcertFinderModel.T_Prefer", "T_Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Tag>("ConcertFinderModel.T_Prefer", "T_Tag", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
